name: HealthTrack CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test: # Nombre del job principal
    runs-on: ubuntu-latest # El job usará una máquina Ubuntu en la nube

    steps:
      # 1. Clona el código del repositorio en el runner
      - name: Checkout código
        uses: actions/checkout@v4

      # 2. Instala Java 17 usando la distribución Temurin
      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Cachea el repositorio local de dependencias de Maven (~/.m2/repository)
      #    Esto acelera el workflow reutilizando dependencias ya descargadas
      - name: Cachear dependencias Maven
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # 4. Compila el proyecto y ejecuta los tests
      #    working-directory indica que Maven debe ejecutarse dentro de la subcarpeta auth-console
      - name: Construir y ejecutar pruebas
        run: mvn clean test
        
  codeql-analysis:
    name: CodeQL Security Analysis
    needs: build-test # Este job solo se ejecuta si el build y los tests pasan.
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write # Permiso necesario para que CodeQL suba los resultados
      actions: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # 1. Inicializa el motor de CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: java # Especifica el lenguaje a analizar

      # 2. Compila el código (esto permite a CodeQL observar el proceso de build)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      # 3. Ejecuta el análisis de CodeQL
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2